version: '3.8'

services:
  trading-engine:
    build:
      context: .
      dockerfile: Dockerfile.trading-engine
    container_name: hft-trading-engine
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "trading_engine"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.websocket-server
    container_name: hft-websocket-server
    ports:
      - "8080:8080"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - trading-engine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hft-frontend
    ports:
      - "80:80"
    depends_on:
      - websocket-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: hft-network